language: node_js
env:
- SSH_USER=root
- DEPLOY_DIRECTORY=/root/1

node_js:
  - node
branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_f21500ed0193_key -iv $encrypted_f21500ed0193_iv
    -in ./id_rsa.enc -out ./id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./id_rsa
  - ssh -i ./id_rsa root@$SSH_HOST pwd

branches:
  only:
  - master

script:
  - echo "npm test temporarily disabled"

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after dir/* $DEPLOY_USER@$SSH_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
