before_install:
- openssl aes-256-cbc -K $encrypted_182589fde6bb_key -iv $encrypted_182589fde6bb_iv -in ./.travis/id_rsa.enc -out ./tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./tmp/id_rsa
- ssh-add .tmp/id_rsa
- ssh -i ./tmp/id_rsa root@$SSH_HOST pwd
