language: node_js
node_js:
  -  stable

branches:
  only:
    - master


addons:
  ssh_known_hosts: $SSH_HOST

script:
  - npm install
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
