before_install:
- openssl aes-256-cbc -K $encrypted_f21500ed0193_key -iv $encrypted_f21500ed0193_iv
  -in ./id_rsa.enc -out ./id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa
- ssh-add ./id_rsa
- ssh -i ./id_rsa root@$SSH_HOST pwd
